### ISSUE TITLE
Add a amigo stop to prevent amigo from constantly asking questions during the other team's turn

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/action_server#40]
In Germany amigo kept on asking what should I do for you while it was Tobi's turn. This happened because amigo was triggered with amigo but after 5 or 6 attempts amigo did not hear something correctly. I think we should implement a amigo stop action. 

-

**Comment by LoyVanBeek** [comment]
What happens when you say "Amigo, stop"? It kills the action server?

Also, maybe include a magic keyword as well that is not often heard 'in the wild'

**Comment by MaxBaeten** [comment]
I think it should not kill the action server but the state machine of the challenge should just switch back to the waiting state and wait for a amigo trigger again.

**Comment by LoyVanBeek** [comment]
Sounds OK and very do-able indeed.

**Comment by MatthijsBurgh** [comment]
I think it is nice to implement this with snowboy, because I don't think the rules allow a external trigger by the iPad. But this is not possible yet with the microphone on the Windows machine.

**Comment by MaxBaeten** [comment]
That was indeed the idea, whether we do this with snowboy or with the regular speech recognition I dont care. But is it possible to use snowboy while at the same time listening for gpsr speech commands with the regular speech recognition?

**Comment by LoyVanBeek** [comment]
Snowboy is for hotwords, after which the regular speech recognition takes over. 

The bug Max describes is that Amigo has been triggered, is waiting for commands, should not get any because it's the other robot's turn but Amigo keeps being annoying by asking for a command.
This command can be to "stop!" asking for more commands. 

When that happens, we should go back in the state machine and then wait until the user calls Amigo again (through a trigger from Snowboy).

**Comment by MaxBaeten** [comment]
closing all GPSR AND EGPRS issues!
